import type { Metadata } from "next";
import React from "react";
import localFont from "next/font/local";
import "./globals.css";
import "@repo/ui/styles.css";
import { ThemeProvider } from "@repo/ui";
import { ThemeToggleHeader } from "./theme-toggle-header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<Readonly<{
  children: React.ReactNode;
}>> = ({
  children,
}) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <ThemeProvider defaultTheme="system" storageKey="web-theme">
          <ThemeToggleHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
